[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
thrust_app = "5LwAeabTKBfiFi5R9mbYwpuU7dbTwSLyHkT8u9hgnVax"

[registry]
url = "https://github.com/thrust-app/thrust-app-contracts"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[workspace]
members = ["programs/thrust_app"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
